data_path = '../data/'
gender_age_train_file_path = data_path + "gender_age_train.csv"
gender_age_test_file_path = data_path +"gender_age_test.csv"
event_file_path = data_path+"events.csv"
app_event_file_path = data_path+"app_events.csv"
app_labels_file_path = data_path+'app_labels.csv'
app_events_device_file_path = data_path+"app_events_device.csv"
app_events_device_applabel_file_path = data_path + "app_events_device_applabel.csv"
app_events_label_file_path = data_path +"app_events_label.csv"
app_labels_dict_file = data_path + "app_labels.dict"
labels_line_num_dict_file = data_path+'label_linenum.dict'
label_categories_file_path = data_path+'label_categories.csv'
app_id_dummies_file_path = data_path + 'app_id_dummies.csv'
device_appid_file_path = data_path+'device_appid.csv'
deviceid_appids_dict_file = data_path + "deviceid_appids_isinstall_isactive.dict"
app_id_less_dummies_file_path = data_path +"app_id_less_dummies.csv"
deviceid_less_dummies_file_path = data_path +"device_id_less_dummies.csv"
phone_brand_device_model_file_path = data_path +'phone_brand_device_model.csv'
